name: Backend CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >
          --health-cmd="mongo --eval 'db.runCommand({ping: 1})'"
          --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        cd backend
        poetry install

    - name: Run tests
      env:
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        MONGODB_URI: 'mongodb://localhost:27017'
        SWARMSTAR_SPACE_DB_NAME: 'swarmstar_tests'
        SWARMSTAR_UI_DB_NAME: 'swarmstar_interface_tests'
      run: |
        cd backend
        poetry run pytest -m "unit and fast"
